# Meta layer for local customizations

BBPATH:prepend := "${LAYERDIR}/:"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "local"
BBFILE_PATTERN_local := "^${LAYERDIR}/"
BBFILE_PRIORITY_local = "1"

LAYERSERIES_COMPAT_local = "scarthgap"
