# Meta-flutter layer configuration
BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb"
BBFILE_COLLECTIONS += "flutter"
BBFILE_PATTERN_flutter := "^${LAYERDIR}/"
BBFILE_PRIORITY_flutter = "6"
LAYERSERIES_COMPAT_flutter = "styhead"
